version: "3.1"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=plenktondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "pgplenkton:/var/lib/postgresql/data"
  test-db:
    image: postgres
    environment:
      - POSTGRES_DB=plenktondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: uvicorn back.__main__:app --host='0.0.0.0' --debug --reload
    container_name: plenkton-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plenktondb
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    build: .
    command: bash -c "cd /code/front && yarn run serve --host 0.0.0.0 --port 3000"
    container_name: plenkton-frontend
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "3000:3000"
  e2e:
    environment:
      - HOST=web
    build:
      context: ./e2e/
    command: /bin/bash
    container_name: playwright
    volumes:
      - ./e2e:/code

volumes:
  pgplenkton:
    external: true
