version: "3.1"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=plenktondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  test-db:
    image: postgres
    environment:
      - POSTGRES_DB=plenktondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: uvicorn back.__main__:app --host='0.0.0.0' --debug --reload
    container_name: plenkton-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plenktondb
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    build:
      context: ./front/
    command: yarn run serve --host 0.0.0.0 --port 3000
    container_name: vuecli-app
    env_file:
      - .env
    volumes:
      - ./front:/code
    ports:
      - "3000:3000"
