on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  upload_dist_to_cloud_storage:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: cd front && yarn install

      - name: Generate dist
        run: cd front && yarn run build
        env:
          DEPLOY: "true"
          CLOUD_BASE_URL: ${{ secrets.CLOUD_BASE_URL }}

      - name: Auth to google cloud
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "front/dist"
          destination: "plenkton/dist"
          parent: false
