name: Backend
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run the tests
        run: poetry run python -m pytest
