name: Plenkton tests
on: [push]
jobs:
  jest:
    runs-on: ubuntu-latest
    name: VueJs Jest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: cd front && yarn install

      - name: Run the tests
        run: cd front && yarn run jest
        env:
          VUE_APP_CLOUD_BASE_URL: ${{ secrets.CLOUD_BASE_URL }}
          VUE_APP_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          VUE_APP_AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
          VUE_APP_AUTH0_FRONT_ID: ${{ secrets.AUTH0_FRONT_ID }}

      - name: Generate dist
        run: cd front && yarn run build

      - name: Share dist folder
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: front/dist

  pytest:
    needs: jest
    runs-on: ubuntu-latest
    name: Python tests
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: plenktondb
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Integrate dist folder
        uses: actions/download-artifact@master
        with:
          name: dist
          path: front/dist

      - name: Run the tests
        run: poetry run python -m pytest back
        env:
          DB_HOST: localhost
          CLOUD_BASE_URL: ${{ secrets.CLOUD_BASE_URL }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_ALGORITHMS: ${{ secrets.AUTH0_ALGORITHMS }}
          AUTH0_FRONT_ID: ${{ secrets.AUTH0_FRONT_ID }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
